FROM node:22-alpine AS build-stage
WORKDIR /build
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build:client

FROM node:22-alpine
WORKDIR /app
COPY --from=build-stage /build/package*.json ./
COPY --from=build-stage /build/dist/apps/client/apps/client ./apps/client
COPY --from=build-stage /build/dist/apps/client/libs ./libs
RUN npm pkg delete scripts.prepare
RUN npm ci --omit=dev
EXPOSE 3000
CMD ["node", "apps/client/src/main"]